# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v3

      # use git pull to master branch instead of git checkout like indicated above
      - name: Pull new changes with git
        run: git pull origin master
        working-directory: /var/www/shaillineshop
        
      - name: Run any migrations tasks
        run: ./yii migrate --interactive=0
        working-directory: /var/www/cms.rckkenya.org
        
        
       # Runs composer install to add or update dependancies
      - name: Install dependancies via composer
        run: |
          echo Installing dependancies
          composer install

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
